# Autogenerated wrapper script for flecs_jll for x86_64-w64-mingw32
export libflecs

JLLWrappers.@generate_wrapper_header("flecs")
JLLWrappers.@declare_library_product(libflecs, "libflecs.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libflecs,
        "bin\\libflecs.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
